const SET_ACTIVE_POINTS = "SET_ACTIVE_POINTS";
const SET_ACTIVE_END_POINT = "SET_ACTIVE_END_POINT";
const SET_ACTIVE_START_POINT = "SET_ACTIVE_START_POINT";

export { SET_ACTIVE_POINTS, SET_ACTIVE_END_POINT, SET_ACTIVE_START_POINT };
