const SET_ACTIVE_POINTS = "SET_ACTIVE_POINTS";
const SET_ORIGIN_POINT = "SET_ORIGIN_POINT";
const SET_DESTINATION_POINT = "SET_DESTINATION_POINT";

export { SET_ACTIVE_POINTS, SET_ORIGIN_POINT, SET_DESTINATION_POINT };
