const SET_ROUTE_POINTS = "SET_ROUTE_POINTS";
const ADD_ROUTE_STOPS = "ADD_ROUTE_STOPS";
const REMOVE_ROUTE_STOP = "REMOVE_ROUTE_STOP";
const SORT_BUS_STOPS = "SORT_BUS_STOPS";
const SORT_BUS_STOP_INDEX = "SORT_BUS_STOP_INDEX";

export {
  SET_ROUTE_POINTS,
  ADD_ROUTE_STOPS,
  REMOVE_ROUTE_STOP,
  SORT_BUS_STOP_INDEX,
  SORT_BUS_STOPS
};
